### ISSUE TITLE
cannot load such file -- zip/zip

### ISSUE THREAD

**Issue by mikabytes** [kremso/serenity#13]
Hi, running MRI 2.0.0 upon starting application it fails with the message:

```
/core_ext/kernel_require.rb:45:in `require': cannot load such file -- zip/zip (LoadError)
/core_ext/kernel_require.rb:45:in `require'
/serenity-odt-0.2.1/lib/serenity/template.rb:1:in `<top (required)>'
```

You don't seem to have a gemspec file, so most likely there's some dependency that isn't available? Or perhaps you rely on something that Rails typically loads? I'm using Sinatra..

**Comment by M1chael** [comment]
`gem 'zip-zip'` instead `gem 'rubyzip'` in Gemfile [solves the issue](https://github.com/rubyzip/rubyzip#important-note).
