### ISSUE TITLE
Incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by Lionel-B** [kremso/serenity#4]
Dear Tomáš,
Using RVM (v1.2.2) + Phusion Passenger (v3.0.2) + different versions of Ruby using RVM: ruby 1.8.7 (patchlevel 330) and ruby 1.9.2  + Rails 3.0.3 on Ubuntu Server 10.04, the application is running after using the "magic encoding" gem. However, Serenity ODT, render_odt is generating the following error:
incompatible character encodings: ASCII-8BIT and UTF-8
Do you an idea and a fix for the library which is very useful for me!
Thanks a lot in advance,
Best Regards,
Lionel.

**Comment by maltesa** [comment]
worked for me as well.
